import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

/// Design System: "Forest & Gilded" — Generated by Stitch MCP
/// Primary: Deep Forest Green #1D3927
/// Secondary: Rich Gold #E9D686
/// Tertiary: Warm Bronze #7D6B35
/// Neutral: Soft Mint #F4F7F3
class AppTheme {
  AppTheme._();

  // ── Brand Colors ──
  static const Color primaryGreen = Color(0xFF1D3927);
  static const Color primaryDark = Color(0xFF062313);
  static const Color accentGold = Color(0xFFE9D686);
  static const Color accentGoldDark = Color(0xFFD9C678);
  static const Color accentGoldDim = Color(0xFFD9C678);
  static const Color tertiaryBronze = Color(0xFF7D6B35);
  static const Color tertiaryContainer = Color(0xFFBFA96D);

  // ── Semantic Status Colors ──
  static const Color statusGreen = Color(0xFF22C55E);
  static const Color statusRed = Color(0xFFEF4444);
  static const Color statusAmber = Color(0xFFF59E0B);
  static const Color statusBlue = Color(0xFF3B82F6);

  // ── Stitch "Forest & Gilded" Color Scheme ──
  static final ColorScheme _colorScheme = ColorScheme(
    brightness: Brightness.light,

    // Primary
    primary: const Color(0xFF062313),
    onPrimary: Colors.white,
    primaryContainer: primaryGreen,
    onPrimaryContainer: const Color(0xFF84A38B),
    primaryFixed: const Color(0xFFCAEBD0),
    primaryFixedDim: const Color(0xFFAECEB5),

    // Secondary (Gold)
    secondary: const Color(0xFF6C5E1B),
    onSecondary: Colors.white,
    secondaryContainer: const Color(0xFFF3E08F),
    onSecondaryContainer: const Color(0xFF70621F),
    secondaryFixed: const Color(0xFFF6E291),
    secondaryFixedDim: accentGoldDim,

    // Tertiary (Bronze)
    tertiary: const Color(0xFF6E5D28),
    onTertiary: Colors.white,
    tertiaryContainer: tertiaryContainer,
    onTertiaryContainer: const Color(0xFF4C3E0B),

    // Surface (Tonal Layering)
    surface: const Color(0xFFF7FAF6),
    onSurface: const Color(0xFF181C1A),
    surfaceContainerLowest: Colors.white,
    surfaceContainerLow: const Color(0xFFF1F4F0),
    surfaceContainer: const Color(0xFFECEFEB),
    surfaceContainerHigh: const Color(0xFFE6E9E5),
    surfaceContainerHighest: const Color(0xFFE0E3DF),
    surfaceBright: const Color(0xFFF7FAF6),
    surfaceDim: const Color(0xFFD8DBD7),
    surfaceTint: const Color(0xFF486550),
    onSurfaceVariant: const Color(0xFF424843),

    // Outline
    outline: const Color(0xFF727972),
    outlineVariant: const Color(0xFFC2C8C1),

    // Error
    error: const Color(0xFFBA1A1A),
    onError: Colors.white,
    errorContainer: const Color(0xFFFFDAD6),
    onErrorContainer: const Color(0xFF93000A),

    // Inverse
    inverseSurface: const Color(0xFF2D312F),
    onInverseSurface: const Color(0xFFEEF2EE),
    inversePrimary: const Color(0xFFAECEB5),

    // Misc
    shadow: const Color(0x0F042110),
    scrim: const Color(0xFF000000),
  );

  // ── Shadow Recipe (from Stitch design doc) ──
  static const List<BoxShadow> ambientShadow = [
    BoxShadow(
      color: Color(0x0F042110), // rgba(4, 33, 16, 0.06)
      blurRadius: 32,
      offset: Offset(0, 12),
    ),
  ];

  static const List<BoxShadow> goldGlow = [
    BoxShadow(
      color: Color(0x40E9D686), // rgba(233, 214, 134, 0.25)
      blurRadius: 20,
      offset: Offset(0, 4),
    ),
  ];

  // ── The Theme ──
  static ThemeData get light {
    final textTheme = GoogleFonts.interTextTheme().copyWith(
      displayLarge: GoogleFonts.inter(
        fontSize: 56,
        fontWeight: FontWeight.w800,
        letterSpacing: -0.02 * 56,
      ),
      displayMedium: GoogleFonts.inter(
        fontSize: 45,
        fontWeight: FontWeight.w700,
        letterSpacing: -0.02 * 45,
      ),
      displaySmall: GoogleFonts.inter(
        fontSize: 36,
        fontWeight: FontWeight.w700,
        letterSpacing: -0.02 * 36,
      ),
      headlineLarge: GoogleFonts.inter(
        fontSize: 32,
        fontWeight: FontWeight.w800,
        letterSpacing: -0.02 * 32,
      ),
      headlineMedium: GoogleFonts.inter(
        fontSize: 28,
        fontWeight: FontWeight.w700,
        letterSpacing: -0.02 * 28,
      ),
      headlineSmall: GoogleFonts.inter(
        fontSize: 24,
        fontWeight: FontWeight.w700,
        letterSpacing: -0.02 * 24,
      ),
      titleLarge: GoogleFonts.inter(
        fontSize: 22,
        fontWeight: FontWeight.w700,
      ),
      titleMedium: GoogleFonts.inter(
        fontSize: 16,
        fontWeight: FontWeight.w600,
      ),
      titleSmall: GoogleFonts.inter(
        fontSize: 14,
        fontWeight: FontWeight.w600,
      ),
      bodyLarge: GoogleFonts.inter(fontSize: 16, fontWeight: FontWeight.w400),
      bodyMedium: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.w400),
      bodySmall: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w400),
      labelLarge: GoogleFonts.inter(
        fontSize: 14,
        fontWeight: FontWeight.w600,
        letterSpacing: 0.04 * 14,
      ),
      labelMedium: GoogleFonts.inter(
        fontSize: 12,
        fontWeight: FontWeight.w600,
        letterSpacing: 0.04 * 12,
      ),
      labelSmall: GoogleFonts.inter(
        fontSize: 11,
        fontWeight: FontWeight.w600,
        letterSpacing: 0.06 * 11,
        textStyle: const TextStyle(
          color: Color(0xFF314D3A), // on_primary_fixed_variant
        ),
      ),
    );

    return ThemeData(
      useMaterial3: true,
      colorScheme: _colorScheme,
      scaffoldBackgroundColor: _colorScheme.surface,
      textTheme: textTheme,
      fontFamily: GoogleFonts.inter().fontFamily,

      // AppBar — uses gradient via flexibleSpace in each screen
      appBarTheme: AppBarTheme(
        backgroundColor: Colors.transparent,
        foregroundColor: _colorScheme.onSurface,
        elevation: 0,
        scrolledUnderElevation: 0,
        titleTextStyle: GoogleFonts.inter(
          fontSize: 28,
          fontWeight: FontWeight.w800,
          color: primaryGreen,
          letterSpacing: -0.02 * 28,
        ),
      ),

      // Cards — NO borders, tonal layering only (Stitch "No-Line Rule")
      cardTheme: CardThemeData(
        color: _colorScheme.surfaceContainerLowest,
        elevation: 0,
        margin: EdgeInsets.zero,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
          side: BorderSide.none, // No-Line Rule
        ),
      ),

      // Chips — pill-shaped, tertiary container
      chipTheme: ChipThemeData(
        backgroundColor: tertiaryContainer,
        labelStyle: GoogleFonts.inter(
          fontWeight: FontWeight.w700,
          fontSize: 12,
          color: const Color(0xFF231A00),
        ),
        shape: const StadiumBorder(),
        side: BorderSide.none,
      ),

      // FilledButton — gradient-like via primary_container
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          backgroundColor: primaryGreen,
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          textStyle: GoogleFonts.inter(
            fontSize: 15,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),

      // NavigationBar — Glassmorphism feel
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: _colorScheme.surfaceContainerLowest.withValues(alpha: 0.92),
        indicatorColor: accentGold.withValues(alpha: 0.2),
        labelTextStyle: WidgetStatePropertyAll(
          GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w600),
        ),
        iconTheme: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) {
            return const IconThemeData(color: primaryGreen, size: 24);
          }
          return IconThemeData(color: _colorScheme.outline, size: 24);
        }),
        elevation: 0,
        surfaceTintColor: Colors.transparent,
      ),

      // Input — surface_container_lowest fill, primary glow on focus
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: _colorScheme.surfaceContainerLowest,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: primaryGreen, width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        labelStyle: GoogleFonts.inter(
          fontSize: 12,
          fontWeight: FontWeight.w600,
          color: _colorScheme.onSurfaceVariant,
        ),
      ),

      // Divider — ghost border (outline_variant at 15%)
      dividerTheme: DividerThemeData(
        color: _colorScheme.outlineVariant.withValues(alpha: 0.15),
        thickness: 1,
      ),

      // FAB — pill-shaped, gold (overridden per-screen)
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: accentGold,
        foregroundColor: primaryDark,
        elevation: 0,
        shape: const StadiumBorder(),
        extendedPadding: const EdgeInsets.symmetric(horizontal: 24),
      ),
    );
  }
}
